Repository pampanic/pam_panic, pull requests merged in 2018-06, with the labels that each got.

#51 Added Japanese MAN pages
  src/pam_panic/man/ja/man8/pam_panic.8
  src/pam_panic_pw/man/ja/man1/pam_panic_pw.1
Labels: localization, question

#53 Fix: Some manpages are not installed.
  src/pam_panic/man/Makefile.am
  src/pam_panic_pw/man/Makefile.am
Labels: bug, localization

#54 .gitignore: *.[0-9].tmp
  .gitignore
Labels: minor, structure
