Repository pampanic/pam_panic, pull requests merged in 2018-04, with the labels that each got.

#22 Adding password function + Refactorization
  Makefile
  README.md
  man/Makefile
  man/de/man1/pam_panic_pw.1
  man/de/man8/pam_panic.8
  man/man1/pam_panic_pw.1
  man/man8/pam_panic.8
  src/Makefile
  src/pam_panic.c
  src/pam_panic/Makefile
  src/pam_panic/pam_panic.c
  src/pam_panic/pam_panic_authdevice.c
  src/pam_panic/pam_panic_authdevice.h
  src/pam_panic/pam_panic_password.c
  src/pam_panic/pam_panic_password.h
  src/pam_panic/pam_panic_reject.c
  src/pam_panic/pam_panic_reject.h
  src/pam_panic_pw/Makefile
  src/pam_panic_pw/pam_panic_pw.c
Labels: enhancement

#27 Correcting and adding header for future unit tests
  Makefile
  README.md
  src/pam_panic/Makefile
  src/pam_panic/pam_panic.c
  src/pam_panic/pam_panic.h
  src/pam_panic/pam_panic_authdevice.c
  src/pam_panic/pam_panic_authdevice.h
  src/pam_panic/pam_panic_password.c
  src/pam_panic/pam_panic_password.h
  src/pam_panic/pam_panic_reject.c
  src/pam_panic/pam_panic_reject.h
  src/pam_panic_pw/pam_panic_pw.c
  src/pam_panic_pw/pam_panic_pw.h
Labels: bug, enhancement

#36 Convert the project to use the GNU Build System (aka Autotools)
  .gitignore
  .travis.yml
  AUTHORS
  COPYING
  ChangeLog
  INSTALL
  Makefile
  Makefile.am
  NEWS
  README
  configure
  configure.ac
  m4/.gitignore
  man/Makefile
  src/Makefile
  src/pam_panic/Makefile
  src/pam_panic/Makefile.am
  src/pam_panic/man/Makefile.am
  src/pam_panic/man/de/man8/pam_panic.8
  src/pam_panic/man/es/man8/pam_panic.8
  src/pam_panic/man/fr/man8/pam_panic.8
  src/pam_panic/man/man8/pam_panic.8
  src/pam_panic/pam_panic.c
  src/pam_panic/pam_panic_password.h
  src/pam_panic/pam_panic_reject.c
  src/pam_panic_pw/Makefile
  src/pam_panic_pw/Makefile.am
  src/pam_panic_pw/man/Makefile.am
  src/pam_panic_pw/man/de/man1/pam_panic_pw.1
  src/pam_panic_pw/man/man1/pam_panic_pw.1
  src/pam_panic_pw/pam_panic_pw.c
Labels: enhancement, major

#40 Might fix #38
  configure.ac
  src/pam_panic/man/Makefile.am
  src/pam_panic/man/de/man8/pam_panic.8
  src/pam_panic/man/es/man8/pam_panic.8
  src/pam_panic/man/fr/man8/pam_panic.8
  src/pam_panic/man/man8/pam_panic.8
  src/pam_panic_pw/man/Makefile.am
  src/pam_panic_pw/man/de/man1/pam_panic_pw.1
  src/pam_panic_pw/man/man1/pam_panic_pw.1
Labels: enhancement, localization
